import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getStyleTokensCss } from "@/lib/styles/repo";
import { getBrandingAssets } from "@/lib/settings/repo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  const { favicon } = await getBrandingAssets();
  return {
    title: "Create Next App",
    description: "Generated by create next app",
    // Falls back to /favicon.ico automatically when no branding favicon is set.
    icons: favicon?.url ? { icon: favicon.url } : undefined,
  };
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const tokensCss = await getStyleTokensCss();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {tokensCss ? (
          <style
            id="aska-style-tokens"
            suppressHydrationWarning
            dangerouslySetInnerHTML={{ __html: tokensCss }}
          />
        ) : null}
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
